name: R CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install R packages
      run: Rscript -e "install.packages(c('testthat'), dependencies=TRUE, repos='http://cran.rstudio.com/')"
    - name: Run tests
      run: Rscript -e "testthat::test_dir('tests/')"
